export const preguntasPareja = [
  "¿Alguna vez me quisiste de verdad?",
  "¿Me fuiste infiel mientras estábamos juntos?",
  "Después de terminar, ¿con cuántas personas te has besado?",
  "¿Qué significo para ti ahora?",
  "Después de todo lo que pasamos, ¿por qué rompimos?",
  "¿Qué se siente no superarme?",
  "¿Qué fue lo más inesperado que descubriste sobre mí después de la ruptura?",
  "¿Alguna vez pensaste en volverme a buscar cuando ya habías terminado con alguien más?",
  "¿Qué es lo que más te molesta de tu vida actual en comparación con cuando estabas conmigo?",
  "¿Hay algo que desearías haberme dicho antes de romper?",
  "¿Con quién te imaginas que has tenido una mejor conexión sexual después de nuestra relación?",
  "¿Qué es lo que más te arrepientes de no haber hecho conmigo?",
  "¿Con qué rapidez pasaste a alguien más después de nuestra ruptura?",
];

export const preguntasAmigos = [
  "¿Has jugado con los sentimientos de alguien?",
  "¿Has sido infiel?",
  "Entre las personas participando, ¿con quién te meterías?",
  "Entre las personas aquí, ¿te cae mal alguna?",
  "Si pudieras volver con algún@ de tus ex, ¿con quién sería?",
  "¿Con cuántas personas te has besado?",
  "¿Te fueron infiel alguna vez?",
  "Entre las personas jugando, ¿le tienes ganas a alguien de aquí?",
  "¿Qué significo para ti?",
  "¿Alguna vez te has enamorado? ¿De quién?",
  "¿Extrañas a tu ex?",
  "¿Volverías con tu ex?",
  "Di la verdad... ¿alguna vez te gustó algún participante del juego?",
  "¿Alguna vez has tenido una aventura con alguien que conocías solo de nombre?",
  "¿Qué es lo más atrevido que has hecho por una noche de fiesta?",
  "¿Has tenido alguna vez una cita desastrosa con alguien que te parecía atractivo en las redes sociales?",
  "¿Quién de tus amigos tiene el peor gusto en parejas?",
  "¿Has tenido alguna vez una atracción secreta por un amigo o amiga de tu círculo cercano?",
  "¿Cuál es la mentira más grande que has dicho para encajar en un grupo social?",
  "¿Qué es lo más vergonzoso que te ha pasado durante una salida con amigos?",
];
